services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - SensorDataMonitoring
    extra_hosts: # Required for Linux
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    networks:
      - SensorDataMonitoring
    extra_hosts: # Required for Linux
      - "host.docker.internal:host-gateway"

networks:
  SensorDataMonitoring:
    external: true